services:

  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - server-side
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example
      SPRING_DATASOURCE_USERNAME: example
      SPRING_DATASOURCE_PASSWORD: example
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_NAME: minioadmin
      MINIO_ACCESS_SECRET: minioadmin
    depends_on:
      db:
          condition: service_healthy
      minio:
          condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
      PGUSER: example
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - server-side
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]

networks:
  server-side:

volumes:
  db-data:
  minio-data:
