services:

  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - server-side
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - server-side
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

networks:
  server-side:

volumes:
  db-data:
  minio-data:
