openapi: 3.0.3
info:
  title: TH1
  description: TH1
  version: 1.0.0

servers:
  - url: 'http://localhost:{port}/v1'
    description: Local server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-dev.virt.uni-oldenburg.de:{port}/v1'
    description: Dev server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-prod.virt.uni-oldenburg.de:{port}/v1'
    description: Prod server
    variables: {
      port: {
        default: '8080'
      }
    }

security:
  - BasicAuth: [ ]

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    tableStructure:
      type: object
      required:
        - name
        - delimiter
        - structures
        - endRow
        - endColumn
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
        delimiter:
          type: string
          maxLength: 1
        structures:
          type: array
          items:
            $ref: '#/components/schemas/structure'
        endRow:
          type: integer
        endColumn:
          type: integer

    structure:
      type: object
      required:
        - converterType
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        columnIndex:
          type: array
          items:
            type: integer
        rowIndex:
          type: array
          items:
            type: integer
        startR:
          type: integer
        startC:
          type: integer
        endR:
          type: integer
        endC:
          type: integer

    tableStructureSummary:
      type: object
      required:
        - id
        - name
        - structures
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
        structures:
          type: array
          items:
            $ref: '#/components/schemas/structureSummary'

    structureSummary:
      type: object
      required:
        - converterType
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'

    converterType:
      type: string
      enum:
        - REMOVE_GROUPED_HEADER
        - FILL_EMPTY_CELLS
        - REMOVE_COLUMN_BY_INDEX
        - REMOVE_ROW_BY_INDEX

paths:
  /table-structures:
    get:
      summary: Get all table structures
      operationId: getTableStructures
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tableStructureSummary'
    post:
      summary: Create a new table structure
      operationId: createTableStructure
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tableStructure'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: 'Table structure created'
  /table-structures/{id}:
    get:
      summary: Get a table structure by id
      operationId: getTableStructure
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tableStructure'

  /converter/{tableStructureId}:
    post:
      summary: Convert a table
      operationId: convertTable
      parameters:
        - name: tableStructureId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ file ]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK

  /converter/preview:
    post:
      summary: Convert a table
      operationId: previewConvertTable
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ file, tableStructure ]
              properties:
                file:
                  type: string
                  format: binary
                tableStructure:
                  $ref: '#/components/schemas/tableStructure'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /converter/full:
    post:
      summary: Convert a table
      operationId: fullConvertTable
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ file, tableStructure ]
              properties:
                file:
                  type: string
                  format: binary
                tableStructure:
                  $ref: '#/components/schemas/tableStructure'
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
