openapi: 3.0.3
info:
  title: TH1
  description: TH1
  version: 1.0.0

servers:
  - url: 'http://localhost:{port}'
    description: Local server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-dev.virt.uni-oldenburg.de:{port}'
    description: Dev server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-prod.virt.uni-oldenburg.de:{port}'
    description: Prod server
    variables: {
      port: {
        default: '8080'
      }
    }

security:
  - BasicAuth: [ ]

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    user:
      $ref: 'schemas/user.yaml'
    tableStructure:
      $ref: 'schemas/tableStructure.yaml'

paths:
  /user/create:
    $ref: "paths/user/create.yaml"

  /transform/save:
    $ref: "paths/transform/save.yaml"
  /transform/get:
    $ref: "paths/transform/get.yaml"
  /transform/execute:
    $ref: "paths/transform/execute.yaml"
