# Example compose file for local development and testing
# DO NOT USE IN PRODUCTION!
# DO NOT USE DEFAULT CREDENTIALS IN PRODUCTION!
# Visit the documentation for more information about deployment (https://github.com/uol-esis/TH1/wiki/Deployment)
name: th1
services:

  backend:
    build: ..
    environment:
      SPRING_DATASOURCE_USERNAME: example
      SPRING_DATASOURCE_PASSWORD: example
      SECURITY_ALLOWED-ORIGINS: http://localhost:5173,http://locahost:8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/example
      SECURITY_AUTHORIZATIONURL: http://localhost:8085/realms/th1/protocol/openid-connect/auth
      SECURITY_TOKENURL: http://localhost:8085/realms/th1/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8085/realms/th1
      SPRINGDOC_SWAGGER-UI_OAUTH_CLIENT-ID: th1
      LOGGING_LEVEL_DE_UOL_PGDOENER_TH1: DEBUG
    network_mode: host # host mode for token verification with keycloak
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
      PGUSER: example
    # Add a volume to the db if you want to reuse uploaded data
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    healthcheck:
      start_period: 5s
      test: [ "CMD-SHELL", "pg_isready" ]

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    ports:
      - "8085:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8085/
    command: [ "start-dev" , "--import-realm" ]
    volumes:
      - "./data/realms:/opt/keycloak/data/import"

# volumes:
#  db-data: