name: th1
services:

  backend:
    build: ..
    ports:
      - "8080:8080"
    networks:
      - server-side
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    ports:
     - "5432:5432"
    env_file:
      - db.env
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    restart: unless-stopped

networks:
  server-side:

volumes:
  db-data: