name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yaml
  docker:
    needs: verify
    uses: ./.github/workflows/docker.yaml
  deploy:
    needs: docker
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute deploy script on dev server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: ${{ secrets.DEPLOY_SCRIPT }}
