name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yaml
  docker:
    needs: verify
    uses: ./.github/workflows/docker.yaml
  deploy:
    needs: docker
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Perform deploy requests
        run: |
          data=$(curl -s ${{ secrets.API_HOST }}/api/stacks/${{ secrets.STACK_ID }}/file \
            -H "X-API-KEY: ${{ secrets.API_KEY }}"  | jq '.StackFileContent')
          wrapped=$(jq -n --argjson data "$data" '{Env:[],id:${{ secrets.STACK_ID }},Prune:false,PullImage:true,StackFileContent: $data}')
          curl -X PUT ${{ secrets.API_HOST }}/api/stacks/${{ secrets.STACK_ID }}?endpointId=${{ secrets.ENDPOINT_ID }} \
            -H "Content-Type: application/json" \
            -H "X-API-KEY: ${{ secrets.API_KEY }}" \
            -d "$wrapped"